import requests
from bs4 import BeautifulSoup
import time
import logging, sys
import random


def get_random_user_agent():
    user_agents = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15",
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
        "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0",
        "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
        "Mozilla/5.0 (iPad; CPU OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/91.0.864.59",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15",
    ]
    return random.choice(user_agents)


logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
import random


def getprodcuctfromlink(h):
    if "dp/" in h:
        return h.split("dp/")[1].split("/")[0]
    if "product-reviews/" in h:
        return h.split("product-reviews/")[1].split("/")[0]
    return h


def getproductsfrompage(
    url="https://www.amazon.com/Best-Sellers-Automotive/zgbs/automotive/ref=zg_bs_nav_automotive_0",
    sleeptime=30,
):
    headers = {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "Accept-Language": "en-US,en;q=0.9",
        "Accept-Encoding": "gzip, deflate, br, zstd",
        "Cache-Control": "max-age=0",
        "Device-Memory": "8",
        "Downlink": "10",
        "User-Agent": get_random_user_agent(),
    }
    a = []
    maxtries = 3
    tries = 0
    while tries < maxtries:
        tries = tries + 1
        response = requests.get(url, headers=headers)
        # print(response.text)
        r = {}
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, "html.parser")
            links = soup.find_all("a", attrs={"class": "a-link-normal"})
            for link in links:
                li = getprodcuctfromlink(link["href"])
                if li and li not in a:
                    a.append(li)
            if sleeptime > 10:
                sleeptime = sleeptime - 1
            return a
        else:
            logging.debug(str(response.status_code) + " - Error loading the page")
            if response.status_code == 404:
                return a
            logging.debug("sleeping " + str(sleeptime))
            time.sleep(sleeptime)
            sleeptime = sleeptime * 2


products = []
urls = [
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing/zgbs/arts-crafts/ref=zg_bs_nav_arts-crafts_0",
    # "https://www.amazon.com/Best-Sellers-Automotive/zgbs/automotive/ref=zg_bs_nav_automotive_0",
    "https://www.amazon.com/Best-Sellers-Baby/zgbs/baby-products/ref=zg_bs_nav_baby-products_0",
    "https://www.amazon.com/Best-Sellers-Beauty-Personal-Care/zgbs/beauty/ref=zg_bs_nav_beauty_0",
    "https://www.amazon.com/best-sellers-camera-photo/zgbs/photo/ref=zg_bs_nav_photo_0",
    "https://www.amazon.com/Best-Sellers-Cell-Phones-Accessories/zgbs/wireless/ref=zg_bs_nav_wireless_0",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories/zgbs/pc/ref=zg_bs_nav_pc_0",
    "https://www.amazon.com/Best-Sellers-Electronics/zgbs/electronics/ref=zg_bs_nav_electronics_0",
    "https://www.amazon.com/Best-Sellers-Health-Household/zgbs/hpc/ref=zg_bs_nav_hpc_0",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen/zgbs/home-garden/ref=zg_bs_nav_home-garden_0",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen/zgbs/home-garden/ref=zg_bs_nav_home-garden_0",
    "https://www.amazon.com/Best-Sellers-Industrial-Scientific/zgbs/industrial/ref=zg_bs_nav_industrial_0",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining/zgbs/kitchen/ref=zg_bs_nav_kitchen_0",
    "https://www.amazon.com/best-sellers-movies-TV-DVD-Blu-ray/zgbs/movies-tv/ref=zg_bs_nav_movies-tv_0",
    "https://www.amazon.com/Best-Sellers-Office-Products/zgbs/office-products/ref=zg_bs_nav_office-products_0",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Garden/zgbs/lawn-garden/ref=zg_bs_nav_lawn-garden_0",
    "https://www.amazon.com/Best-Sellers-Pet-Supplies/zgbs/pet-supplies/ref=zg_bs_nav_pet-supplies_0",
    "https://www.amazon.com/Best-Sellers-Sports-Outdoors/zgbs/sporting-goods/ref=zg_bs_nav_sporting-goods_0",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Improvement/zgbs/hi/ref=zg_bs_nav_hi_0",
    "https://www.amazon.com/Best-Sellers-Toys-Games/zgbs/toys-and-games/ref=zg_bs_nav_toys-and-games_0",
    "https://www.amazon.com/Best-Sellers-Appliances/zgbs/appliances/ref=zg_bs_nav_appliances_0",
    "https://www.amazon.com/Best-Sellers-Appliances-Cooktops/zgbs/appliances/3741261/ref=zg_bs_nav_appliances_1",
    "https://www.amazon.com/Best-Sellers-Appliances-Dishwashers/zgbs/appliances/3741271/ref=zg_bs_nav_appliances_1_3741261",
    "https://www.amazon.com/Best-Sellers-Appliances-Freezers/zgbs/appliances/3741331/ref=zg_bs_nav_appliances_1",
    "https://www.amazon.com/Best-Sellers-Appliances-Ice-Makers/zgbs/appliances/2399939011/ref=zg_bs_nav_appliances_1",
    "https://www.amazon.com/Best-Sellers-Appliances-Range-Hoods/zgbs/appliances/3741441/ref=zg_bs_nav_appliances_1_2399939011",
    "https://www.amazon.com/Best-Sellers-Appliances-Ranges/zgbs/appliances/3741411/ref=zg_bs_nav_appliances_1_3741441",
    "https://www.amazon.com/Best-Sellers-Appliances-Refrigerators/zgbs/appliances/3741361/ref=zg_bs_nav_appliances_1",
    "https://www.amazon.com/Best-Sellers-Appliances-Wall-Ovens/zgbs/appliances/3741481/ref=zg_bs_nav_appliances_1_3741361",
    "https://www.amazon.com/Best-Sellers-Appliances-Warming-Drawers/zgbs/appliances/2399955011/ref=zg_bs_nav_appliances_1",
    "https://www.amazon.com/Best-Sellers-Appliances-Washers-Dryers/zgbs/appliances/2383576011/ref=zg_bs_nav_appliances_1_2399955011",
    "https://www.amazon.com/Best-Sellers-Appliances-Wine-Cellars/zgbs/appliances/3741521/ref=zg_bs_nav_appliances_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Beading-Jewelry-Making/zgbs/arts-crafts/12896081/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Craft-Supplies-Materials/zgbs/arts-crafts/378733011/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Craft-Hobby-Fabric/zgbs/arts-crafts/12899121/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Craft-Hobby-Fabric/zgbs/arts-crafts/12899121/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Knitting-Crochet-Supplies/zgbs/arts-crafts/12897221/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Needlework-Supplies/zgbs/arts-crafts/2237329011/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Arts-Crafts-Sewing-Storage/zgbs/arts-crafts/2237594011/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Arts-Crafts-Sewing-Storage/zgbs/arts-crafts/2237594011/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Painting-Drawing-Art-Supplies/zgbs/arts-crafts/2747968011/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Scrapbooking-Photo-Transfer-Coloring/zgbs/arts-crafts/12898411/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Sewing-Products/zgbs/arts-crafts/12899091/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Sewing-Thread-Floss/zgbs/arts-crafts/12897331/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Arts-Crafts-Sewing-Yarn/zgbs/arts-crafts/262625011/ref=zg_bs_nav_arts-crafts_1",
    "https://www.amazon.com/Best-Sellers-Automotive-Car-Care/zgbs/automotive/15718271/ref=zg_bs_nav_automotive_1",
    "https://www.amazon.com/Best-Sellers-Automotive-Cleaning-Kits/zgbs/automotive/15718281/ref=zg_bs_nav_automotive_2_15718271",
    "https://www.amazon.com/Best-Sellers-Automotive-Exterior-Care-Products/zgbs/automotive/15718291/ref=zg_bs_nav_automotive_2_15718271",
    "https://www.amazon.com/Best-Sellers-Automotive-Automotive-Fillers-Adhesives-Sealants/zgbs/automotive/21557050011/ref=zg_bs_nav_automotive_2_15718271",
    "https://www.amazon.com/Best-Sellers-Automotive-Finishing-Products/zgbs/automotive/15718501/ref=zg_bs_nav_automotive_2_15718271",
    "https://www.amazon.com/Best-Sellers-Automotive-Glass-Care-Products/zgbs/automotive/15718531/ref=zg_bs_nav_automotive_2_15718271",
    "https://www.amazon.com/Best-Sellers-Automotive-Interior-Care-Products/zgbs/automotive/15718541/ref=zg_bs_nav_automotive_2_15718271",
    "https://www.amazon.com/Best-Sellers-Automotive-Tire-Wheel-Care-Products/zgbs/automotive/15718641/ref=zg_bs_nav_automotive_2_15718271",
    "https://www.amazon.com/Best-Sellers-Automotive-Tools-Equipment/zgbs/automotive/15718651/ref=zg_bs_nav_automotive_2_15718271",
    "https://www.amazon.com/Best-Sellers-Automotive-Undercoatings/zgbs/automotive/15718781/ref=zg_bs_nav_automotive_2_15718271",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Activity-Entertainment-Products/zgbs/baby-products/239225011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Care-Products/zgbs/baby-products/17720255011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Child-Safety-Car-Seats-Accessories/zgbs/baby-products/166835011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Diapering-Products/zgbs/baby-products/166764011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Toddler-Feeding-Supplies/zgbs/baby-products/166777011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Pregnancy-Maternity-Products/zgbs/baby-products/166804011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Gifts/zgbs/baby-products/239226011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Nursery-Furniture-Bedding-Dcor/zgbs/baby-products/695338011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Toilet-Training-Products/zgbs/baby-products/166887011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Safety-Products/zgbs/baby-products/166863011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Strollers/zgbs/baby-products/166842011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Travel-Gear/zgbs/baby-products/17726796011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Beauty-Personal-Care-Foot-Hand-Nail-Care-Products/zgbs/beauty/17242866011/ref=zg_bs_nav_beauty_1",
    "https://www.amazon.com/Best-Sellers-Beauty-Personal-Care-Beauty-Gift-Sets/zgbs/beauty/120225719011/ref=zg_bs_nav_beauty_1",
    "https://www.amazon.com/Best-Sellers-Beauty-Personal-Care-Hair-Care-Products/zgbs/beauty/11057241/ref=zg_bs_nav_beauty_1",
    "https://www.amazon.com/Best-Sellers-Beauty-Personal-Care-Skin-Care-Products/zgbs/beauty/11060451/ref=zg_bs_nav_beauty_1",
    "https://www.amazon.com/Best-Sellers-Beauty-Personal-Care-Beauty-Tools-Accessories/zgbs/beauty/11062741/ref=zg_bs_nav_beauty_1",
    "https://www.amazon.com/Best-Sellers-Camera-Photo-Products-Camera-Photo-Accessories/zgbs/photo/172435/ref=zg_bs_nav_photo_1",
    "https://www.amazon.com/Best-Sellers-Camera-Photo-Products-Camera-Bags-Cases/zgbs/photo/172437/ref=zg_bs_nav_photo_1",
    "https://www.amazon.com/Best-Sellers-Camera-Photo-Products-Binoculars-Telescopes-Optics/zgbs/photo/499320/ref=zg_bs_nav_photo_1",
    "https://www.amazon.com/Best-Sellers-Camera-Photo-Products-Camcorders/zgbs/photo/172421/ref=zg_bs_nav_photo_1",
    "https://www.amazon.com/Best-Sellers-Camera-Photo-Products-DSLR-Cameras/zgbs/photo/3017941/ref=zg_bs_nav_photo_1",
    "https://www.amazon.com/Best-Sellers-Camera-Photo-Products-Digital-Picture-Frames/zgbs/photo/525460/ref=zg_bs_nav_photo_1",
    "https://www.amazon.com/Best-Sellers-Camera-Photo-Products-Camcorder-Camera-Lenses/zgbs/photo/499248/ref=zg_bs_nav_photo_1",
    "https://www.amazon.com/Best-Sellers-Camera-Photo-Products-Digital-Point-Shoot-Cameras/zgbs/photo/330405011/ref=zg_bs_nav_photo_1",
    "https://www.amazon.com/Best-Sellers-Camera-Photo-Products-Surveillance-Security-Cameras/zgbs/photo/898400/ref=zg_bs_nav_photo_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_pc_0_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Accessories-Peripherals/zgbs/pc/172456/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Components/zgbs/pc/193870011/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Data-Storage/zgbs/pc/1292110011/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Desktop-Computers/zgbs/pc/565098/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-External-Components/zgbs/pc/3012292011/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Laptop-Accessories/zgbs/pc/3011391011/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Laptop-Computers/zgbs/pc/565108/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Monitors/zgbs/pc/1292115011/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Networking/zgbs/pc/172504/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Printers/zgbs/pc/172635/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Routers/zgbs/pc/300189/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Scanners/zgbs/pc/172584/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Servers/zgbs/pc/11036071/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Tablet-Accessories/zgbs/pc/2348628011/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Tablets/zgbs/pc/1232597011/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers-Computers-Accessories-Computer-Warranties-Services/zgbs/pc/16285851/ref=zg_bs_nav_pc_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_electronics_0_1",
    "https://www.amazon.com/Best-Sellers-Electronics-El…bs/electronics/281407/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Ca…bs/electronics/502394/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Ca…s/electronics/1077068/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Ce…lectronics/2811119011/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Co…bs/electronics/541966/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-GP…bs/electronics/172526/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-He…bs/electronics/172541/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Ho…electronics/667846011/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Ma…electronics/319574011/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Of…bs/electronics/172574/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Po…bs/electronics/172623/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Se…bs/electronics/524136/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Co…/electronics/16285901/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Te…lectronics/1266092011/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Vi…lectronics/7926841011/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-Vi…bs/electronics/300334/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-We…ectronics/10048700011/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers-Electronics-eB…lectronics/2642125011/ref=zg_bs_nav_electronics_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_entertainment-collectibles_0_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…352011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…598011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…511011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…599011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…600011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…351011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…140011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…604011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…605011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…157011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…881011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…607011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…078011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…532011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…609011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…942011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…608011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…611011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…612011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…613011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…614011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…492011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…615011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…616011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…617011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…618011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…619011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…610011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…620011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…621011/ref=zg_bs_nav_entertainment-collectibles_1",
    "https://www.amazon.com/Best-Sellers-Entertainment-…624011/ref=zg_bs_nav_entertainment-collectibles_1"
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_hpc_0_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…re-Products/zgbs/hpc/10787321/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…ts-Nutrition/zgbs/hpc/3764441/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…are-Products/zgbs/hpc/3760941/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…ld-Supplies/zgbs/hpc/15342811/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…es-Equipment/zgbs/hpc/3775161/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…Products/zgbs/hpc/10079992011/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…are-Products/zgbs/hpc/3777891/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…s-Deals/zgbs/hpc/120225718011/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…ess-Products/zgbs/hpc/3777371/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…-Products/zgbs/hpc/6973663011/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…g-Supplies/zgbs/hpc/723418011/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…Products/zgbs/hpc/10079994011/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…plements/zgbs/hpc/23675621011/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers-Health-Househo…Products/zgbs/hpc/10079996011/ref=zg_bs_nav_hpc_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_home-garden_0_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-B…s/home-garden/1063236/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-B…s/home-garden/1063252/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-H…/home-garden/10802561/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-F…s/home-garden/1063306/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-H…ome-garden/3206324011/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-H…s/home-garden/1063278/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-I…bs/home-garden/510240/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-K…ome-garden/3206325011/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-K…bs/home-garden/284507/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-S…/home-garden/13679381/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-H…s/home-garden/3610841/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-V…bs/home-garden/510106/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers-Home-Kitchen-W…s/home-garden/3736081/ref=zg_bs_nav_home-garden_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_industrial_0_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…s/industrial/256167011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…/industrial/6066126011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…s/industrial/256225011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…industrial/10773802011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…/industrial/5772192011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…s/industrial/383598011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…industrial/18746931011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…s/industrial/383599011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…/industrial/3061625011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…/industrial/6054382011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…/industrial/3021479011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…s/industrial/306506011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…bs/industrial/16412251/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…s/industrial/317971011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…s/industrial/317970011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…s/industrial/256346011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…s/industrial/318135011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…/industrial/8553197011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…/industrial/3021459011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…bs/industrial/16310181/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…/industrial/8297371011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…/industrial/8297370011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…bs/industrial/16310191/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…/industrial/8615538011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…/industrial/8498884011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…s/industrial/393459011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers-Industrial-Sci…s/industrial/256409011/ref=zg_bs_nav_industrial_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_kitchen_0_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…eware/zgbs/kitchen/289668/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…kware/zgbs/kitchen/289728/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…ances/zgbs/kitchen/289742/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…kware/zgbs/kitchen/289814/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…ing/zgbs/kitchen/13162311/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…are/zgbs/kitchen/13217501/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…ng/zgbs/kitchen/979832011/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…nens/zgbs/kitchen/1063916/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…dgets/zgbs/kitchen/289754/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…ances/zgbs/kitchen/289913/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…ation/zgbs/kitchen/510136/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers-Kitchen-Dining…ies/zgbs/kitchen/13299291/ref=zg_bs_nav_kitchen_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_musical-instruments_0_1",
    "https://www.amazon.com/Best-Sellers-Musical-Instru…nts/405758011/ref=zg_bs_nav_musical-instruments_1",
    "https://www.amazon.com/Best-Sellers-Musical-Instru…ents/11971311/ref=zg_bs_nav_musical-instruments_1",
    "https://www.amazon.com/Best-Sellers-Musical-Instru…ents/11973881/ref=zg_bs_nav_musical-instruments_1",
    "https://www.amazon.com/Best-Sellers-Musical-Instru…ents/11970241/ref=zg_bs_nav_musical-instruments_1",
    "https://www.amazon.com/Best-Sellers-Musical-Instru…ents/11971241/ref=zg_bs_nav_musical-instruments_1",
    "https://www.amazon.com/Best-Sellers-Musical-Instru…ents/11965871/ref=zg_bs_nav_musical-instruments_1",
    "https://www.amazon.com/Best-Sellers-Musical-Instru…ents/11969981/ref=zg_bs_nav_musical-instruments_1",
    "https://www.amazon.com/Best-Sellers-Musical-Instru…nts/405757011/ref=zg_bs_nav_musical-instruments_1",
    "https://www.amazon.com/Best-Sellers-Musical-Instru…ents/11973111/ref=zg_bs_nav_musical-instruments_1",
    "https://www.amazon.com/Best-Sellers-Musical-Instru…s/14733114011/ref=zg_bs_nav_musical-instruments_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_office-products_0_1",
    "https://www.amazon.com/Best-Sellers-Office-Product…products/12899801/ref=zg_bs_nav_office-products_1",
    "https://www.amazon.com/Best-Sellers-Office-Product…-products/1068972/ref=zg_bs_nav_office-products_1",
    "https://www.amazon.com/Best-Sellers-Office-Product…e-products/172574/ref=zg_bs_nav_office-products_1",
    "https://www.amazon.com/Best-Sellers-Office-Product…-products/1069102/ref=zg_bs_nav_office-products_1",
    "https://www.amazon.com/Best-Sellers-Office-Product…-products/1068956/ref=zg_bs_nav_office-products_1",
    "https://www.amazon.com/Best-Sellers-Office-Product…-products/1069242/ref=zg_bs_nav_office-products_1",
    "https://www.amazon.com/Best-Sellers-Office-Product…-products/1069254/ref=zg_bs_nav_office-products_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_lawn-garden_0_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…awn-garden/4619352011/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…s/lawn-garden/3610851/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…bs/lawn-garden/552808/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…bs/lawn-garden/553760/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…bs/lawn-garden/551242/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…bs/lawn-garden/553788/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…wn-garden/13638732011/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…/lawn-garden/13400641/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…bs/lawn-garden/553824/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…bs/lawn-garden/553844/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…awn-garden/1272941011/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers-Patio-Lawn-Gar…s/lawn-garden/3043471/ref=zg_bs_nav_lawn-garden_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_pet-supplies_0_1",
    "https://www.amazon.com/Best-Sellers-Pet-Supplies-P…-supplies/2975221011/ref=zg_bs_nav_pet-supplies_1",
    "https://www.amazon.com/Best-Sellers-Pet-Supplies-C…-supplies/2975241011/ref=zg_bs_nav_pet-supplies_1",
    "https://www.amazon.com/Best-Sellers-Pet-Supplies-D…-supplies/2975312011/ref=zg_bs_nav_pet-supplies_1",
    "https://www.amazon.com/Best-Sellers-Pet-Supplies-F…-supplies/2975446011/ref=zg_bs_nav_pet-supplies_1",
    "https://www.amazon.com/Best-Sellers-Pet-Supplies-H…-supplies/2975481011/ref=zg_bs_nav_pet-supplies_1",
    "https://www.amazon.com/Best-Sellers-Pet-Supplies-R…-supplies/2975504011/ref=zg_bs_nav_pet-supplies_1",
    "https://www.amazon.com/Best-Sellers-Pet-Supplies-S…-supplies/2975520011/ref=zg_bs_nav_pet-supplies_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_sporting-goods_0_1",
    "https://www.amazon.com/Best-Sellers-Sports-Outdoor…ting-goods/3394801/ref=zg_bs_nav_sporting-goods_1",
    "https://www.amazon.com/Best-Sellers-Sports-Outdoor…ting-goods/3407731/ref=zg_bs_nav_sporting-goods_1",
    "https://www.amazon.com/Best-Sellers-Sports-Outdoor…ting-goods/3386071/ref=zg_bs_nav_sporting-goods_1",
    "https://www.amazon.com/Best-Sellers-Sports-Outdoor…ng-goods/706813011/ref=zg_bs_nav_sporting-goods_1",
    "https://www.amazon.com/Best-Sellers-Sports-Outdoor…g-goods/2358921011/ref=zg_bs_nav_sporting-goods_1",
    "https://www.amazon.com/Best-Sellers-Sports-Outdoor…ng-goods/706814011/ref=zg_bs_nav_sporting-goods_1",
    "https://www.amazon.com/Best-Sellers-Sports-Outdoor…-goods/10971181011/ref=zg_bs_nav_sporting-goods_1",
    "https://www.amazon.com/Best-Sellers-Sports-Outdoor…ting-goods/3422351/ref=zg_bs_nav_sporting-goods_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_hi_0_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…red-Tools/zgbs/hi/120225786011/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…me-Appliances/zgbs/hi/13397451/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…ilding-Supplies/zgbs/hi/551240/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…rical-Equipment/zgbs/hi/495266/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…vement-Hardware/zgbs/hi/511228/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…-Bath-Fixtures/zgbs/hi/3754161/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…ng-Ceiling-Fans/zgbs/hi/495224/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…easuring-Layout/zgbs/hi/553244/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…tments-Supplies/zgbs/hi/228899/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…s-Hand-Tools/zgbs/hi/328182011/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…ing-Equipment/zgbs/hi/13749581/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…afety-Security/zgbs/hi/3180231/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers-Tools-Home-Imp…-Organization/zgbs/hi/13400631/ref=zg_bs_nav_hi_1",
    "https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bs_unv_toys-and-games_0_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Toy…nd-games/165993011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Art…nd-games/166057011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Bab…nd-games/196601011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Tri…nd-games/256994011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Bui…nd-games/166092011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Col…nd-games/166242011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Dol…nd-games/166118011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Kid…nd-games/166316011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Kid…nd-games/166164011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Gam…nd-games/166220011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Lea…nd-games/166269011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Kid…nd-games/166326011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Nov…nd-games/166027011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Kid…d-games/1266203011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Toy…-games/23539911011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Pre…games/120225720011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Pup…nd-games/166333011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Puz…nd-games/166359011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Hob…d-games/6925830011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Spo…nd-games/166420011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/Best-Sellers-Toys-Games-Stu…nd-games/166461011/ref=zg_bs_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/ref=zg_bsnr_nav_arts-crafts_0",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12896081/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/378733011/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12899121/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12896841/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12897221/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12897221/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/2237329011/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/2237594011/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/2747968011/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12898411/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12898451/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12898821/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12899091/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12897331/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12897331/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/262625011/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/appliances/ref=zg_bsnr_nav_appliances_0",
    "https://www.amazon.com/gp/new-releases/appliances/3741261/ref=zg_bsnr_nav_appliances_1",
    "https://www.amazon.com/gp/new-releases/appliances/3741271/ref=zg_bsnr_nav_appliances_1",
    "https://www.amazon.com/gp/new-releases/appliances/3741331/ref=zg_bsnr_nav_appliances_1",
    "https://www.amazon.com/gp/new-releases/appliances/2399939011/ref=zg_bsnr_nav_appliances_1",
    "https://www.amazon.com/gp/new-releases/appliances/3741441/ref=zg_bsnr_nav_appliances_1",
    "https://www.amazon.com/gp/new-releases/appliances/3741411/ref=zg_bsnr_nav_appliances_1",
    "https://www.amazon.com/gp/new-releases/appliances/3741361/ref=zg_bsnr_nav_appliances_1",
    "https://www.amazon.com/gp/new-releases/appliances/3741481/ref=zg_bsnr_nav_appliances_1",
    "https://www.amazon.com/gp/new-releases/appliances/2399955011/ref=zg_bsnr_nav_appliances_1",
    "https://www.amazon.com/gp/new-releases/appliances/2383576011/ref=zg_bsnr_nav_appliances_1",
    "https://www.amazon.com/gp/new-releases/appliances/3741521/ref=zg_bsnr_nav_appliances_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12896081/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/378733011/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/378733011/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12899121/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12896841/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12897221/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/2237329011/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/2237594011/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/2747968011/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12898411/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12898411/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12898411/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12898821/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12899091/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/12897331/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/arts-crafts/262625011/ref=zg_bsnr_nav_arts-crafts_1",
    "https://www.amazon.com/gp/new-releases/automotive/ref=zg_bsnr_nav_automotive_0",
    "https://www.amazon.com/gp/new-releases/automotive/15718271/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/gp/new-releases/automotive/15857511/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/gp/new-releases/automotive/15857501/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/gp/new-releases/automotive/15736321/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/gp/new-releases/automotive/15736321/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/gp/new-releases/automotive/346333011/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/gp/new-releases/automotive/346333011/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/gp/new-releases/automotive/2258019011/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/gp/new-releases/automotive/15719731/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/gp/new-releases/automotive/15706941/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/gp/new-releases/automotive/15706941/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/gp/new-releases/automotive/15706571/ref=zg_bsnr_nav_automotive_1",
    "https://www.amazon.com/Best-Sellers-Baby/zgbs/baby-products/ref=zg_bs_nav_baby-products_0",
    "https://www.amazon.com/Best-Sellers-Baby/zgbs/baby-products/ref=zg_bs_nav_baby-products_0",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Care-Products/zgbs/baby-products/17720255011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Child-Safety-Car-Seats-Accessories/zgbs/baby-products/166835011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Diapering-Products/zgbs/baby-products/166764011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Toddler-Feeding-Supplies/zgbs/baby-products/166777011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Gifts/zgbs/baby-products/239226011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Nursery-Furniture-Bedding-Dcor/zgbs/baby-products/695338011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Toilet-Training-Products/zgbs/baby-products/166887011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Safety-Products/zgbs/baby-products/166863011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Strollers/zgbs/baby-products/166842011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/Best-Sellers-Baby-Baby-Travel-Gear/zgbs/baby-products/17726796011/ref=zg_bs_nav_baby-products_1",
    "https://www.amazon.com/gp/new-releases/beauty/ref=zg_bsnr_nav_beauty_0",
    "https://www.amazon.com/gp/new-releases/beauty/17242866011/ref=zg_bsnr_nav_beauty_1",
    "https://www.amazon.com/gp/new-releases/beauty/17242866011/ref=zg_bsnr_nav_beauty_1",
    "https://www.amazon.com/gp/new-releases/beauty/120225719011/ref=zg_bsnr_nav_beauty_1",
    "https://www.amazon.com/gp/new-releases/beauty/11057241/ref=zg_bsnr_nav_beauty_1",
    "https://www.amazon.com/gp/new-releases/beauty/11058281/ref=zg_bsnr_nav_beauty_1",
    "https://www.amazon.com/gp/new-releases/beauty/11062741/ref=zg_bsnr_nav_beauty_1",
    "https://www.amazon.com/gp/new-releases/photo/ref=zg_bsnr_nav_photo_0",
    "https://www.amazon.com/gp/new-releases/photo/172435/ref=zg_bsnr_nav_photo_1",
    "https://www.amazon.com/gp/new-releases/photo/172437/ref=zg_bsnr_nav_photo_1",
    "https://www.amazon.com/gp/new-releases/photo/499320/ref=zg_bsnr_nav_photo_1",
    "https://www.amazon.com/gp/new-releases/photo/172421/ref=zg_bsnr_nav_photo_1",
    "https://www.amazon.com/gp/new-releases/photo/3017941/ref=zg_bsnr_nav_photo_1",
    "https://www.amazon.com/gp/new-releases/photo/525460/ref=zg_bsnr_nav_photo_1",
    "https://www.amazon.com/gp/new-releases/photo/499248/ref=zg_bsnr_nav_photo_1",
    "https://www.amazon.com/gp/new-releases/photo/330405011/ref=zg_bsnr_nav_photo_1",
    "https://www.amazon.com/gp/new-releases/photo/898400/ref=zg_bsnr_nav_photo_1",
    "https://www.amazon.com/gp/new-releases/pc/ref=zg_bsnr_nav_pc_0",
    "https://www.amazon.com/gp/new-releases/pc/ref=zg_bsnr_nav_pc_0",
    "https://www.amazon.com/gp/new-releases/pc/193870011/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/pc/1292110011/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/pc/3012292011/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/pc/3011391011/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/pc/565108/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/pc/1292115011/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/pc/172504/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/pc/172635/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/pc/300189/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/pc/172584/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/pc/2348628011/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/pc/11036071/ref=zg_bsnr_nav_pc_1",
    "https://www.amazon.com/gp/new-releases/electronics/2348628011/ref=zg_bsnr_nav_electronics_2_11036071",
    "https://www.amazon.com/gp/new-releases/electronics/15524379011/ref=zg_bsnr_nav_electronics_2_11036071",
    "https://www.amazon.com/gp/new-releases/electronics/ref=zg_bsnr_nav_electronics_0_digital-educational-resources",
    "https://www.amazon.com/gp/new-releases/electronics/281407/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/502394/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/1077068/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/2811119011/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/541966/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/172526/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/172541/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/667846011/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/319574011/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/172574/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/172623/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/524136/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/1266092011/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/7926841011/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/300334/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/10048700011/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/electronics/2642125011/ref=zg_bsnr_nav_electronics_1",
    "https://www.amazon.com/gp/new-releases/home-garden/ref=zg_bsnr_nav_home-garden_0_digital-educational-resources",
    "https://www.amazon.com/gp/new-releases/home-garden/1063236/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/home-garden/1063252/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/home-garden/1063306/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/home-garden/3206324011/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/home-garden/1063278/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/home-garden/510240/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/home-garden/3206325011/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/home-garden/284507/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/home-garden/13679381/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/home-garden/3610841/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/home-garden/510106/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/home-garden/3736081/ref=zg_bsnr_nav_home-garden_1",
    "https://www.amazon.com/gp/new-releases/kitchen/ref=zg_bsnr_nav_kitchen_0",
    "https://www.amazon.com/gp/new-releases/kitchen/289668/ref=zg_bsnr_nav_kitchen_1",
    "https://www.amazon.com/gp/new-releases/kitchen/289728/ref=zg_bsnr_nav_kitchen_1",
    "https://www.amazon.com/gp/new-releases/kitchen/289742/ref=zg_bsnr_nav_kitchen_1",
    "https://www.amazon.com/gp/new-releases/kitchen/289814/ref=zg_bsnr_nav_kitchen_1",
    "https://www.amazon.com/gp/new-releases/kitchen/13162311/ref=zg_bsnr_nav_kitchen_1",
    "https://www.amazon.com/gp/new-releases/kitchen/979832011/ref=zg_bsnr_nav_kitchen_1",
    "https://www.amazon.com/gp/new-releases/kitchen/289754/ref=zg_bsnr_nav_kitchen_1",
    "https://www.amazon.com/gp/new-releases/kitchen/289913/ref=zg_bsnr_nav_kitchen_1",
    "https://www.amazon.com/gp/new-releases/kitchen/510136/ref=zg_bsnr_nav_kitchen_1",
    "https://www.amazon.com/gp/new-releases/kitchen/510136/ref=zg_bsnr_nav_kitchen_1",
    "https://www.amazon.com/gp/new-releases/kitchen/13299291/ref=zg_bsnr_nav_kitchen_1",
    "https://www.amazon.com/gp/new-releases/musical-instruments/ref=zg_bsnr_nav_musical-instruments_0",
    "https://www.amazon.com/gp/new-releases/musical-instruments/405758011/ref=zg_bsnr_nav_musical-instruments_1",
    "https://www.amazon.com/gp/new-releases/musical-instruments/11971311/ref=zg_bsnr_nav_musical-instruments_1",
    "https://www.amazon.com/gp/new-releases/musical-instruments/11973881/ref=zg_bsnr_nav_musical-instruments_1",
    "https://www.amazon.com/gp/new-releases/musical-instruments/11970241/ref=zg_bsnr_nav_musical-instruments_1",
    "https://www.amazon.com/gp/new-releases/musical-instruments/11971241/ref=zg_bsnr_nav_musical-instruments_1",
    "https://www.amazon.com/gp/new-releases/musical-instruments/11965871/ref=zg_bsnr_nav_musical-instruments_1",
    "https://www.amazon.com/gp/new-releases/musical-instruments/11969981/ref=zg_bsnr_nav_musical-instruments_1",
    "https://www.amazon.com/gp/new-releases/musical-instruments/11973111/ref=zg_bsnr_nav_musical-instruments_1",
    "https://www.amazon.com/gp/new-releases/musical-instruments/11973111/ref=zg_bsnr_nav_musical-instruments_1",
    "https://www.amazon.com/gp/new-releases/musical-instruments/14733114011/ref=zg_bsnr_nav_musical-instruments_1",
    "https://www.amazon.com/gp/new-releases/office-products/ref=zg_bsnr_nav_office-products_0",
    "https://www.amazon.com/gp/new-releases/office-products/12899801/ref=zg_bsnr_nav_office-products_1",
    "https://www.amazon.com/gp/new-releases/office-products/1068972/ref=zg_bsnr_nav_office-products_1",
    "https://www.amazon.com/gp/new-releases/office-products/172574/ref=zg_bsnr_nav_office-products_1",
    "https://www.amazon.com/gp/new-releases/office-products/1069102/ref=zg_bsnr_nav_office-products_1",
    "https://www.amazon.com/gp/new-releases/office-products/1068956/ref=zg_bsnr_nav_office-products_1",
    "https://www.amazon.com/gp/new-releases/office-products/1069242/ref=zg_bsnr_nav_office-products_1",
    "https://www.amazon.com/gp/new-releases/office-products/1069254/ref=zg_bsnr_nav_office-products_1",
    "https://www.amazon.com/gp/new-releases/lawn-garden/ref=zg_bsnr_nav_lawn-garden_0",
    "https://www.amazon.com/gp/new-releases/lawn-garden/4619352011/ref=zg_bsnr_nav_lawn-garden_1",
    "https://www.amazon.com/gp/new-releases/lawn-garden/3610851/ref=zg_bsnr_nav_lawn-garden_1",
    "https://www.amazon.com/gp/new-releases/lawn-garden/552808/ref=zg_bsnr_nav_lawn-garden_1",
    "https://www.amazon.com/gp/new-releases/lawn-garden/553760/ref=zg_bsnr_nav_lawn-garden_1",
    "https://www.amazon.com/gp/new-releases/lawn-garden/551242/ref=zg_bsnr_nav_lawn-garden_1",
    "https://www.amazon.com/gp/new-releases/lawn-garden/553788/ref=zg_bsnr_nav_lawn-garden_1",
    "https://www.amazon.com/gp/new-releases/lawn-garden/13638732011/ref=zg_bsnr_nav_lawn-garden_1",
    "https://www.amazon.com/gp/new-releases/lawn-garden/13400641/ref=zg_bsnr_nav_lawn-garden_1",
    "https://www.amazon.com/gp/new-releases/lawn-garden/553824/ref=zg_bsnr_nav_lawn-garden_1",
    "https://www.amazon.com/gp/new-releases/lawn-garden/1272941011/ref=zg_bsnr_nav_lawn-garden_1",
    "https://www.amazon.com/gp/new-releases/lawn-garden/1272941011/ref=zg_bsnr_nav_lawn-garden_1",
    "https://www.amazon.com/gp/new-releases/pet-supplies/ref=zg_bsnr_nav_pet-supplies_0",
    "https://www.amazon.com/gp/new-releases/pet-supplies/2975221011/ref=zg_bsnr_nav_pet-supplies_1",
    "https://www.amazon.com/gp/new-releases/pet-supplies/2975241011/ref=zg_bsnr_nav_pet-supplies_1",
    "https://www.amazon.com/gp/new-releases/pet-supplies/2975312011/ref=zg_bsnr_nav_pet-supplies_1",
    "https://www.amazon.com/gp/new-releases/pet-supplies/2975446011/ref=zg_bsnr_nav_pet-supplies_1",
    "https://www.amazon.com/gp/new-releases/pet-supplies/2975481011/ref=zg_bsnr_nav_pet-supplies_1",
    "https://www.amazon.com/gp/new-releases/pet-supplies/2975481011/ref=zg_bsnr_nav_pet-supplies_1",
    "https://www.amazon.com/gp/new-releases/pet-supplies/2975504011/ref=zg_bsnr_nav_pet-supplies_1",
    "https://www.amazon.com/gp/new-releases/pet-supplies/2975520011/ref=zg_bsnr_nav_pet-supplies_1",
    "https://www.amazon.com/gp/new-releases/sporting-goods/ref=zg_bsnr_nav_sporting-goods_0",
    "https://www.amazon.com/gp/new-releases/sporting-goods/3394801/ref=zg_bsnr_nav_sporting-goods_1",
    "https://www.amazon.com/gp/new-releases/sporting-goods/3407731/ref=zg_bsnr_nav_sporting-goods_1",
    "https://www.amazon.com/gp/new-releases/sporting-goods/3386071/ref=zg_bsnr_nav_sporting-goods_1",
    "https://www.amazon.com/gp/new-releases/sporting-goods/706813011/ref=zg_bsnr_nav_sporting-goods_1",
    "https://www.amazon.com/gp/new-releases/sporting-goods/2358921011/ref=zg_bsnr_nav_sporting-goods_1",
    "https://www.amazon.com/gp/new-releases/sporting-goods/706814011/ref=zg_bsnr_nav_sporting-goods_1",
    "https://www.amazon.com/gp/new-releases/sporting-goods/10971181011/ref=zg_bsnr_nav_sporting-goods_1",
    "https://www.amazon.com/gp/new-releases/sporting-goods/3422351/ref=zg_bsnr_nav_sporting-goods_1",
    "https://www.amazon.com/gp/new-releases/hi/ref=zg_bsnr_nav_hi_0",
    "https://www.amazon.com/gp/new-releases/hi/120225786011/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/13397451/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/551240/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/495266/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/511228/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/3754161/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/495224/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/553244/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/228899/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/13749581/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/328182011/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/3180231/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/hi/13400631/ref=zg_bsnr_nav_hi_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/ref=zg_bsnr_nav_toys-and-games_0",
    "https://www.amazon.com/gp/new-releases/toys-and-games/165993011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166057011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/196601011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/256994011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166092011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166242011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166118011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166316011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166164011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166220011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166269011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166326011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166326011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/1266203011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/23539911011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/120225720011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/23539911011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/120225720011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166359011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/6925830011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/6925830011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166420011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166420011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/toys-and-games/166461011/ref=zg_bsnr_nav_toys-and-games_1",
    "https://www.amazon.com/gp/new-releases/boost/ref=zg_bsnr_nav_boost_0",
    "https://www.amazon.com/gp/movers-and-shakers/arts-crafts/ref=zg_bsms_nav_arts-crafts_0",
    "https://www.amazon.com/gp/movers-and-shakers/automotive/ref=zg_bsms_nav_automotive_0_audible",
    "https://www.amazon.com/gp/movers-and-shakers/baby-products/ref=zg_bsms_nav_baby-products_0_automotive",
    "https://www.amazon.com/gp/movers-and-shakers/beauty/ref=zg_bsms_nav_beauty_0_baby-products",
    "https://www.amazon.com/gp/movers-and-shakers/photo/ref=zg_bsms_nav_photo_0_beauty",
    "https://www.amazon.com/gp/movers-and-shakers/music/ref=zg_bsms_nav_music_0_photo",
    "https://www.amazon.com/gp/movers-and-shakers/wireless/ref=zg_bsms_nav_wireless_0_music",
    "https://www.amazon.com/gp/movers-and-shakers/climate-pledge/ref=zg_bsms_nav_climate-pledge_0_wireless",
    "https://www.amazon.com/gp/movers-and-shakers/fashion/ref=zg_bsms_nav_fashion_0_climate-pledge",
    "https://www.amazon.com/gp/movers-and-shakers/coins/ref=zg_bsms_nav_coins_0_fashion",
    "https://www.amazon.com/gp/movers-and-shakers/pc/ref=zg_bsms_nav_pc_0_coins",
    "https://www.amazon.com/gp/movers-and-shakers/electronics/ref=zg_bsms_nav_electronics_0_digital-educational-resources",
    "https://www.amazon.com/gp/movers-and-shakers/entertainment-collectibles/ref=zg_bsms_nav_entertainment-collectibles_0_electronics",
    "https://www.amazon.com/gp/movers-and-shakers/grocery/ref=zg_bsms_nav_grocery_0_gift-cards",
    "https://www.amazon.com/gp/movers-and-shakers/handmade/ref=zg_bsms_nav_handmade_0_grocery",
    "https://www.amazon.com/gp/movers-and-shakers/hpc/ref=zg_bsms_nav_hpc_0_handmade",
    "https://www.amazon.com/gp/movers-and-shakers/home-garden/ref=zg_bsms_nav_home-garden_0_hpc",
    "https://www.amazon.com/gp/movers-and-shakers/digital-text/ref=zg_bsms_nav_digital-text_0_home-garden",
    "https://www.amazon.com/gp/movers-and-shakers/kitchen/ref=zg_bsms_nav_kitchen_0_digital-text",
    "https://www.amazon.com/gp/movers-and-shakers/musical-instruments/ref=zg_bsms_nav_musical-instruments_0_kitchen",
    "https://www.amazon.com/gp/movers-and-shakers/office-products/ref=zg_bsms_nav_office-products_0_musical-instruments",
    "https://www.amazon.com/gp/movers-and-shakers/lawn-garden/ref=zg_bsms_nav_lawn-garden_0_office-products",
    "https://www.amazon.com/gp/movers-and-shakers/pet-supplies/ref=zg_bsms_nav_pet-supplies_0_lawn-garden",
    "https://www.amazon.com/gp/movers-and-shakers/sporting-goods/ref=zg_bsms_nav_sporting-goods_0_software",
    "https://www.amazon.com/gp/movers-and-shakers/sports-collectibles/ref=zg_bsms_nav_sports-collectibles_0_sporting-goods",
    "https://www.amazon.com/gp/movers-and-shakers/hi/ref=zg_bsms_nav_hi_0_sports-collectibles",
    "https://www.amazon.com/gp/movers-and-shakers/toys-and-games/ref=zg_bsms_nav_toys-and-games_0_hi",
    "https://www.amazon.com/gp/movers-and-shakers/boost/ref=zg_bsms_nav_boost_0_toys-and-games",
    "https://www.amazon.com/gp/movers-and-shakers/videogames/ref=zg_bsms_nav_videogames_0_boost",
]

# todo add subcategories of new products starting with unique finds
count = 0
max = 30
for url in urls:
    logging.debug("num products found: " + str(len(products)))
    try:
        if len(products) < max:
            logging.debug(url)
            newproducts = getproductsfrompage(url)
            for p in newproducts:
                if p not in products:
                    products.append(p)
    except Exception as e:
        # print(e)
        pass
for p in products:
    print(p)
